# Generated by Django 4.2.6 on 2025-04-09 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qouraApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questions",
            name="slug",
        ),
    ]
