# Generated by Django 4.2 on 2025-04-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qouraApp', '0002_remove_questions_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
